version: '3.5'

services:
    redis:
        image: redis:7.2.4
        ports:
        - "6379:6379"

    nginx:
        image: nginx:latest
        volumes:
          - ./Configs/nginx.conf:/etc/nginx/nginx.conf:ro
        ports:
          - "9999:9999"
        deploy:
            resources:
                limits:
                    cpus: "0.1"
                    memory: "50MB"